minesweeper_1:
  discount_factor_g: 0.95
  env_make_params:
    board:
      height: 6
      width: 6
      num_mines: 3
  epsilon_decay: 0.9999
  epsilon_init: 1.0
  epsilon_min: 0.05
  fc1_nodes: 64
  learning_rate_a: 0.00025 
  mini_batch_size: 64
  network_sync_rate: 1000
  replay_memory_size: 250000

  enable_flagging: True  
